/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class helixdown_testing_com_ndk_file_encrypt_NDKFilePatch */

#ifndef _Included_helixdown_testing_com_ndk_file_encrypt_NDKFilePatch
#define _Included_helixdown_testing_com_ndk_file_encrypt_NDKFilePatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     helixdown_testing_com_ndk_file_encrypt_NDKFilePatch
 * Method:    Diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_helixdown_testing_com_ndk_1file_1encrypt_NDKFilePatch_Diff
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     helixdown_testing_com_ndk_file_encrypt_NDKFilePatch
 * Method:    Patch
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_helixdown_testing_com_ndk_1file_1encrypt_NDKFilePatch_Patch
  (JNIEnv *, jclass, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
