/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class helixdown_testing_com_ndk_file_encrypt_Cryptor */

#ifndef _Included_helixdown_testing_com_ndk_file_encrypt_Cryptor
#define _Included_helixdown_testing_com_ndk_file_encrypt_Cryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     helixdown_testing_com_ndk_file_encrypt_Cryptor
 * Method:    Encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_helixdown_testing_com_ndk_1file_1encrypt_Cryptor_Encrypt
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     helixdown_testing_com_ndk_file_encrypt_Cryptor
 * Method:    Decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_helixdown_testing_com_ndk_1file_1encrypt_Cryptor_Decrypt
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
